"""empty message

Revision ID: 367d81b171f7
Revises: 
Create Date: 2020-03-17 09:11:04.656869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367d81b171f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('emotion', sa.String(length=1), nullable=True))
    op.add_column('analytics', sa.Column('operator', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'operator')
    op.drop_column('analytics', 'emotion')
    # ### end Alembic commands ###
