"""empty message

Revision ID: ace47e087b7d
Revises: 367d81b171f7
Create Date: 2020-03-25 18:45:47.326522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace47e087b7d'
down_revision = '367d81b171f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'type')
    # ### end Alembic commands ###
